### ISSUE TITLE
Error reported

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#13]
[V1024-EBF][ERR] Failed to apply Harmony patches for V1024.EBFramework. Exception was: HarmonyLib.HarmonyException: Patching exception in method virtual System.Void Verse.DamageWorker_Blunt::ApplySpecialEffectsToPart(Verse.Pawn pawn, System.Single totalDamage, Verse.DamageInfo dinfo, Verse.DamageResult result) ---> System.FormatException: Method virtual System.Void Verse.DamageWorker_Blunt::ApplySpecialEffectsToPart(Verse.Pawn pawn, System.Single totalDamage, Verse.DamageInfo dinfo, Verse.DamageResult result) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) Verse.DamageWorker_Blunt:Verse.DamageWorker_Blunt.ApplySpecialEffectsToPart_Patch0 (Verse.DamageWorker_Blunt,Verse.Pawn,single,Verse.DamageInfo,Verse.DamageWorker/DamageResult): IL_02b6: call 0x000000af

at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x0008c] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x000bb] in <c38a8c3281a047488dac8c9d063b7abb>:0
--- End of inner exception stack trace ---
at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HarmonyLib.PatchClassProcessor.Patch () [0x00082] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) [0x00007] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <c38a8c3281a047488dac8c9d063b7abb>:0
at HugsLib.ModBase.ApplyHarmonyPatches () [0x0009a] in <a56dbe2cf5184fe991f5fb736b3081b0>:0
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
HugsLib.Utils.ModLogger:Error (string,object[])
HugsLib.ModBase:ApplyHarmonyPatches ()
HugsLib.HugsLibController:EnumerateChildMods (bool)
HugsLib.HugsLibController:LoadReloadInitialize ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by Vectorial1024** [comment]
Steam user further reports that this is caused by HAR.

**Comment by Vectorial1024** [comment]
Another Steam user provides this log/message:

------

I have the same bug, but my log is very slightly different. In my log, instead of

"HugsLib.HugsLibController:EnumerateChildMods (bool)
HugsLib.HugsLibController:LoadReloadInitialize ()"

I got

"(wrapper dynamic-method) HugsLib.HugsLibController:HugsLib.HugsLibController.EnumerateChildMods_Patch1 (HugsLib.HugsLibController,bool)
(wrapper dynamic-method) HugsLib.HugsLibController:HugsLib.HugsLibController.LoadReloadInitialize_Patch1 (HugsLib.HugsLibController)"

No idea if it helps, but there you go.

------

Hopefully we will have the time to deal with this, but no guarantees, real life is busy.

**Comment by Vectorial1024** [comment]
I finally got around to verify this. Indeed we have a problem with Humanoid Alien Races (HAR). However when I tried to read the code of HAR I cannot understand how they managed to patch anything that might be relevant to the erronous section of code. Maybe something more is going on...

**Comment by sharkman** [comment]
Meanwhile I've trying to fix my save game (upon upgrading to 1.3) and got similar message towards the end of the log: https://gist.github.com/cec80301d29bb18c2abf06f22ae64976

Humanoid Alien Races is indeed involved in that, but their patching code is to complicated for me to understand:
https://github.com/erdelf/AlienRaces/blob/f7ab85f9a80ebf7a35cf9a494adf8edbbc000eac/Source/AlienRace/AlienRace/HarmonyPatches.cs

**Comment by Vectorial1024** [comment]
Hi there!

While I think I kind of understand what the HAR patching code is supposed to do, the fun thing about this issue is that I literally cannot find any occurence to anything like "ApplySpecialEffectsToPart" in the patching method. Right now it is just seemingly unexplainable: how can they modify a method that they did not even specify to modify?

Or I just need to open up the decompiler for once and have a look, but I am getting a bit lazy recently.

**Comment by Vectorial1024** [comment]
You know what, screw this, I will just retcon my mod to discontinue that fragment of feature for everyone. Aint got no time dealing with computer magic.

But I will leave this open cuz we really didn't solve this problem; we only disappeared the problem.

**Comment by sharkman** [comment]
I've read through their code in regards to my error log, it references `AlienRace.HarmonyPatches.BodyReferenceTranspiler`... well, so basically on the lines 375-390 in the file below they are not looking for a specific method to patch, but rather patch everything that remotely looks like their patching criteria, and their patching criteria is a field `FieldInfo bodyInfo = AccessTools.Field(typeof(RaceProperties), nameof(RaceProperties.body));`, whatever that is (again, I'm not good at this): https://github.com/erdelf/AlienRaces/blob/f7ab85f9a80ebf7a35cf9a494adf8edbbc000eac/Source/AlienRace/AlienRace/HarmonyPatches.cs#L375
```C#
                FieldInfo bodyInfo = AccessTools.Field(typeof(RaceProperties), nameof(RaceProperties.body));
                MethodInfo bodyCheck = AccessTools.Method(patchType, nameof(ReplacedBody));
                HarmonyMethod bodyTranspiler = new HarmonyMethod(patchType, nameof(BodyReferenceTranspiler));

                //Full assemblies scan
                foreach (MethodInfo mi in typeof(LogEntry).Assembly.GetTypes().
                    SelectMany(t => t.GetNestedTypes(AccessTools.all).Concat(t)).
                    Where(predicate: t => (!t.IsAbstract || t.IsSealed) && !typeof(Delegate).IsAssignableFrom(t) && !t.IsGenericType).SelectMany(selector: t =>
                        t.GetMethods(AccessTools.all).Concat(t.GetProperties(AccessTools.all).SelectMany(selector: pi => pi.GetAccessors(nonPublic: true)))
                      .Where(predicate: mi => mi != null && !mi.IsAbstract && mi.DeclaringType == t && !mi.IsGenericMethod && !mi.HasAttribute<DllImportAttribute>())).Distinct()// && mi.GetMethodBody()?.GetILAsByteArray()?.Length > 1))
                ) //.Select(mi => mi.IsGenericMethod ? mi.MakeGenericMethod(mi.GetGenericArguments()) : mi))
                {
                    IEnumerable<KeyValuePair<OpCode, object>> instructions = PatchProcessor.ReadMethodBody(mi);
                    if (mi != bodyCheck && instructions.Any(predicate: il => il.Value?.Equals(bodyInfo) ?? false))
                        harmony.Patch(mi, transpiler: bodyTranspiler);
                }
```

**Comment by Vectorial1024** [comment]
Oh so actually it was two different ppl... because I basically got a PR for this issue at right about the same time #14 I am getting confused about that lol

Anyways. I now have a rough idea what is going on after reading this and #14. What I believe is going on is that they want to insert a prefix/postfix to redirect BodyPart access to the HAR framework BodyPart, but because of some C# technical limitations, there cannot be any prefix/postfix. So they opted to do a full-assembly scan to replace the vanilla accessor to their custom accessor, which apparently breaks this mod which is trying to rewrite/append some extra code after specific BodyPart accessors.

**Comment by Vectorial1024** [comment]
OK #14 it works!

Closing this. I have never expected HAR to do a full assembly scan at first, but now things are clearer and solved. Thanks for the help!
