### ISSUE TITLE
Lag in Caravan Screen

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#32]
Multiple Steam users report extreme lag with the Caravan UI. It would seem to originate from the People and Animals tab in some of the caravan GUIs.

Not sure what is going on for the moment, but perhaps there are some unexpected side effect that I did not notice, or there are some hidden assumptions that I used + does not hold in the relevant GUI screens.

Or, maybe there are some hidden optimizations that can be done, just like how I previously improved the performance of Real Time Clock Plus just by discovering and using the `ToStringCached` function instead of the usual `ToString`.

What is strangest, is that there are no error logs. This rules out exception-based lag, but rather logic-based lag.

Regardless, a deeper look is needed.

**Comment by SeppDE** [comment]
If more informations are needed just tag me here.

**Comment by Vectorial1024** [comment]
The main deal with the `v5.*` family is about Community Unification, which basically means using C# reflection to execute functions that would otherwise require separate patch mods if made by the less tech-abled modders.

Because we are using reflection, the performace will be poorer than directly using machine code in the C# dlls, but I expected that "it wont be that bad"...

From the attached log it seems something is going on with AchievementsExpanded.AchievementCard ...?

I also see your tracing screenshot, but just in case, which tool were you using to get that info? I want to explore a bit on my side to see if I can get something similar, also to get familiar with using profilers etc.

**Comment by seldonPlan** [comment]
The tool is Dub's Performance Analyzer, on [steam](https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626)... 

I use a fork of that project by user @simplyWiri of that project with some slight re-tooling of the UI, and some additional troubleshooting categories https://github.com/simplyWiri/Dubs-Performance-Analyzer

For what it's worth, there is also a pretty active performance optimization focused discord group: https://discord.com/channels/241677926855081984/660280287497814078 , i've seen the folks over there help other mod authors with stuff like this

**Comment by seldonPlan** [comment]
as for my log, there is definitely something borked with the Achievements expanded. I yanked that mod mid-way through my current play through and i am still seeing some vestigial issues that i havent been able to fix. That said, i dont think that is the particular issue here. I run quite a few other mods with minimal issues, and my machine seems to keep up fine with a TPS in high 300's at 3x speed (without EBF, that is)

**Comment by Vectorial1024** [comment]
For Achievements Expanded, my guess is that it injected some string value into some savedata, and those strings are actually defNames of Achievement Expanded data structures.

It keeps throwing errors because the savedata could be loaded fine (ie not corrupted) but the game could not find the defs as specified by the string.

I'll just setup the profiler first and investigate later.

**Comment by Vectorial1024** [comment]
I opened up the profiler, and indeed there is a great lag, and with my rather powerful laptop, it only showed up as an (personally) acceptable fps drop. It was not outright unusable so it slipped past unnoticed.

One thing to notice is that there are many many calls to GetMaxHealth , which does not seem right...? it is mainly the many calls to GetMaxHealth that is causing the lag.

**Comment by Sindusk** [comment]
I noticed it becomes outright unusable when you have a significant amount of pawns. The issue directly scales with how many pawns are displayed on the screen, and I noticed it becomes essentially unusable around 20 pawns. Not noticeable early on, but **very** noticeable later in the game.

**Comment by Vectorial1024** [comment]
Every computer system becomes unusable when there is too much going on, but becoming unusable with only 20 pawns is unacceptable.

Something is going on with the seemingly excessive amount of calls to the GetMaxHealth function.

**Comment by Vectorial1024** [comment]
I do not know why the function had to be called many many times, but apparently the most number of calls came from

- HediffSet GetPartHealth
- Pawn Capacity calculation
- Moody UI display

In fact when I think about it, when we are forming caravans the game will be paused, so eventually most of those calls are expecting the same value. Might as well cache those values for a great peerformance boost.

I will release the update later, but when testing locally with the Performance Analyser, the performance is now greatly improved, to the point where there is virtually no performance impact whatsoever:

![Screenshot](https://user-images.githubusercontent.com/17726797/179347208-206758b9-d7b2-4cb6-be79-3f0eb187573e.png)

I'll see if I can also deal with #33 and push them both in the same update.

**Comment by Vectorial1024** [comment]
I'm closing this because v5.0.4 (released) has solved this.
