### ISSUE TITLE
Error with Ultratech ACR (?)

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#33]
Steam user reports sus-ed error with Ultratech: Altered Carbon Remastered, with this (partial) log: https://gist.github.com/c2i39400/89624e3d2b5a4cb79f59a421dd0e3f6d

They also mention also using Quality Bionics, but from the stacktrace I feel like maybe Pawnmorpher is (also) being used.

**Comment by jllllll** [comment]
I'm also getting this error. Here is my log: https://gist.github.com/jllllll/0aaca6c62f03d42b5410e61f717d3d36

I am more or less using this collection on Steam here: https://steamcommunity.com/sharedfiles/filedetails/?id=2674631666

I first downloaded this mod at version 5.0.1, but have since updated to the latest version. Both versions had this error.

**Comment by c2i39400** [comment]
I think it is because Quality Bionics, cause I found that other bionics/implants from other mods have same issue, which also have "From: QualityBionics Base HP: x" in the tooltip.

**Comment by jllllll** [comment]
Removing Quality Bionics from my mod list seems to have fixed the tooltips for me.

**Comment by jllllll** [comment]
Implants from SNS AOTC: Custom Edition and Science Never Stops seem to also cause the error.

**Comment by Vectorial1024** [comment]
I checked again, this report coincides with a Pawnmorpher update. This means that Pawnmorpher must have updated their code...

Will investigate.

**Comment by jllllll** [comment]
That may be, however I was having this bug both before and after updating Pawnmorpher.

**Comment by Vectorial1024** [comment]
So, to conclude, you got this error when:

- you are using pawnmorpher
- you are/are not using eg science never stops
- you are/are not using quality bionics

Is this correct?

**Comment by jllllll** [comment]
I am using all of those, yes. To be clear, this error occurs on all artificial parts when quality bionics is enabled. Without quality bionics, I only see it occurring with science never stops parts.

**Comment by Vectorial1024** [comment]
It seems I cannot reproduce this. I did it by using this:

1. Install + enable QualityBionics and Pawnmorpher
2. Start a fresh map (or open a game that has only been recently started)
3. Use debug command to add hediff to clean pawns
4. Check the tooltip of hediffs
5. Sees no problem

On an separate occassion, I also tested installing bionics that has quality on them onoto pawns, and the result is shown on the Steam Workshop screenshot with no problems.

Can you describe what kind of situation your pawn is in? EG are they using some bionics, they are somewhat mutated by Pawnmorpher, and you are looking at their tooltip...? Something like that?

**Comment by jllllll** [comment]
The error occurs at any point in the game, even at character creation. I linked the collection that I am using along with my HugsLib log in my first comment. I'll do some more testing with removing mods on my end.

**Comment by jllllll** [comment]
Narrowed down my mod list to just a few mods as shown in this log: https://gist.github.com/jllllll/70a263ff7c8269bb99926d63350a944c

Error was reproduced by randomizing pawn in selection screen until getting one with a prosthetic part. However, upon deleting \*ConfigFolder*\HugsLib\SpottedMods.xml, the error no longer appeared. Strange stuff.

**Comment by jllllll** [comment]
Reloading my full mod list causes the error to reappear. This makes me think that none of my testing was effective at all. It seems that, somehow, elements of previously loaded mods are being loaded despite the associated mods being disabled. Even deleting RocketMan's files doesn't prevent this. I'm going to throw in the towel here as I have no clue why this is happening and it is preventing accurate testing.

**Comment by Vectorial1024** [comment]
> It seems that, somehow, elements of previously loaded mods are being loaded 

Yeah...

I also noticed this a long time ago. Apparently, mods and etc will write their information somewhere else, because sometimes when I disable mods + look at the debug log, I notice the game complaining about "cannot find [concept from mod]".

-------

One thing I want to point out, is that I currently do not own any of the RW DLCs (because I dont have too much time playing with them anyways); hopefully this is NOT the reason why I cannot reproduce the error.

------

This problem is much deeper than expected, so even when we do not have any clear clues yet, thank you for your help in looking into this problem!

**Comment by Vectorial1024** [comment]
Update:

I am not sure whether I have unexpectdly solved this error in v5.0.4 because when I was reviewing the code, one line of them was sus, and I applied a fix without knowing how it worked or even thinking whether it was important.

See if it helped.

**Comment by jllllll** [comment]
The error does appear to be fixed now! May keep testing a bit longer just to be sure. Also just letting you know, while the EBF violation warning for Pawnmorpher no longer appears at game start, it still appears at world gen.

**Comment by Vectorial1024** [comment]
Aha! So it was that problem. For future C# programmers: apparently if we need to reflect-call a function with optional parameters (as in `GetMutationTracker`, signature was `this Pawn, bool = ...`), we need to insert a special value into the parameters list (source https://stackoverflow.com/questions/2421994/invoking-methods-with-optional-parameters-through-reflection ). We cannot just not insert it as if we are using C# regularly.

Probably don't need to test for too long because it is the kind of error where I did something wrongly with C#. Nothing to do with game features etc.

I'll just fix it properly and then mark this as complete.

------

As to the `Pawnmorpher violates EBF Protocol` error, it is actually harmless, and you can refer to #34 for future updates.

**Comment by Vectorial1024** [comment]
v5.0.5 with this fix is released on Steam, so I am closing this.
