### ISSUE TITLE
Lag spikes again!

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#55]
We optimized for RimThreaded in #54 , but unfortunately, Steam user reports lag spikes again... The user claimed that they are not using RimThreaded.

Some early observations:

- #54 made use of `ConcurrentDictionary`, but unfortunately, for RimWorld (running on NET v4), `ConcurrentDictionary` is extra slow (ref https://stackoverflow.com/questions/15252115/concurrentdictionary-performance-at-a-single-thread-misunderstanding)
- We are listening for health cache invalidation, but the problem is that the invalidation is triggered too often; eg if the pawn is healing, the injury hediff ticks, and the cache is invalidated already. Not good.
- The cache itself did save a lot of recalculation (as seen in #54 ), which is good

These are the problems that we have to address in the immediate next version.

**Comment by Vectorial1024** [comment]
For even more reference: https://github.com/Vectorial1024/EliteBionicsFramework/issues/53

**Comment by Vectorial1024** [comment]
Dev profiling:

![Screenshot 2023-04-23 234558](https://user-images.githubusercontent.com/17726797/233849891-84667f8f-3043-4c0b-9246-fa69237755a0.png)

Seeing how "Avg Time/Update" dropped to 0.077ms I guess this is already an improvement?

Besides, the actual numbers seems highly dependent on what is going on in the game maps and the "world map".

**Comment by kacpeG** [comment]
![rim](https://user-images.githubusercontent.com/75324317/233977704-6775ea7c-9943-4927-bc27-77078eb38e1f.png)
I dont know if i should post this here but, i have really bad lag spikes from this mod as you can see in the screenshot

**Comment by Vectorial1024** [comment]
Hi there

I only read this just now...

I have just now released an update to the mod, to try to fix the performance-related problems. Is there any improvement?

Some other things may also be helpful:
- Would there be too many pawns in the map?
- How is your PC stats?
- Were there any heavy fighting etc, something that will affect pawns' health?

It is normal to have random spikes when the game is asking for never-before-calculated values (eg, you just bought a few pigs, and you start to read the stats of those pigs), but if it spikes too often, then it is a problem.

**Comment by kacpeG** [comment]
After this update there are no more big stutters but there are still stutters, so something you did kinda worked but, still there are times when the calls jump by like 1k in half a second and in that time the game lags. 
Can i i somehow help you figure out what might be the problem?
![image](https://user-images.githubusercontent.com/75324317/234391062-3fcf7fe5-2edf-49e3-aa84-95b137ce231d.png)

**Comment by Vectorial1024** [comment]
Good to hear that the big lags have gone away.

It seems unusual to have 1k calls that happen in the same second, or maybe I do not understand the game well enough yet.

When I was testing, I also noticed some random spikes happening.

You can help check these easy-to-see things:
- Are there many pawns?
- Are there many fighting happening?
- Are you having a lot of farm animals? (Note: my guess is about "too many farm animals grow up too fast")

Other than the above easy-to-see things that you can help check, the remaining causes I will need to insert debug log on my side and on my test map to understand how the game works.

**Comment by Vectorial1024** [comment]
Note: I noticed that Compact Hediff might be related to the lag spike problem.

It seems they are calling the uncached max-HP method, which can really kill performance. There is a reason why the cached method exists: it skips the bulk of the calculation.

This is very obvious when you try to read the hediff info of destroyed body parts.

**Comment by Vectorial1024** [comment]
Another update was released to reduce lag even further. EG, performance with CompactHediff is now improved, along with performance with the vanilla game itself.

See if it helped.

**Comment by kacpeG** [comment]
The thing that was causing errors before is fixed, now the only thing that causes lag is this
![image](https://user-images.githubusercontent.com/75324317/235441332-feb04b72-6d80-486b-992b-c6ba69c8d914.png)

**Comment by Vectorial1024** [comment]
The top line is about a MSE2 function call from Medical Systems Expansion 2. And then I cannot see any direct connections between EBF and MSE2.

But still, you see that there are no EBF-named functions in the lag list anymore, which means the EBF optimizations are quite successful.

Some mods will unavoidably produce lag due to their complexity, but perhaps you may want to contact MSE2 about potential performance optimizations. See if they can optimize their performance.

**Comment by Vectorial1024** [comment]
Still, I think there is yet just a bit more optimization to be done... but that optimization will focus on cleaning up, and will not impact much if you have a lot of pawns already.

**Comment by Vectorial1024** [comment]
The clean-up optimization is now released.

At this moment, I cannot think of any further optimizations that can still be done to EBF.

Therefore, closing this.
