### ISSUE TITLE
error between EBF and EdB

### ISSUE THREAD

**Issue by BladedWolf** [Vectorial1024/EliteBionicsFramework#9]
[V1024-EBF]  Elite Bionics Framework has detected some mods using the unmodified GetMaxHealth() method, which violates the EBF protocol. The author(s) of the involved mod(s) should adopt the EBF to clarify their intentions.
For now, the unmodified max HP is returned.
The detected mod comes from: EdB.PrepareCarefully
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
EBF.EliteBionicsFrameworkMain:LogError(String, Boolean)
EBF.Patches.Prefix_BodyPart_GetMaxHealth:PreFix(BodyPartDef, Single, Pawn)
Verse.BodyPartDef:Verse.BodyPartDef.GetMaxHealth_Patch3(BodyPartDef, Pawn)
EdB.PrepareCarefully.Injury:InitializeTooltip()
EdB.PrepareCarefully.Injury:get_Tooltip()
EdB.PrepareCarefully.PanelHealth:DrawCustomBodyPart(Single, CustomBodyPart, Field)
EdB.PrepareCarefully.PanelHealth:DrawCustomBodyParts(Single)
EdB.PrepareCarefully.PanelHealth:DrawPanelContent(State)
EdB.PrepareCarefully.PanelBase:Draw(State)
EdB.PrepareCarefully.TabViewPawns:Draw(State, Rect)
EdB.PrepareCarefully.Page_PrepareCarefully:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by Vectorial1024** [comment]
Imma just notify EdB Prepare Carefully about this and let them decide whhat to do with this, because this mod added extra context to what "max HP" means, and it is best to give it to the users to decide what they mean by "max HP".

**Comment by Vectorial1024** [comment]
Update: I totally forgot whether I have notified Prepare Carefully about this, and to be honest I may have overestimated the influence that my mod is supposed to have.

I'll see if I can also get this to work on my side then.
